/*
 * c8080 stdlib
 * Copyright (c) 2025 Aleksey Morozov aleksey.f.morozov@gmail.com aleksey.f.morozov@yandex.ru
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#pragma codepage reset

#pragma codepage('─', 0x80)
#pragma codepage('│', 0x81)
#pragma codepage('┌', 0x82)
#pragma codepage('┐', 0x83)
#pragma codepage('└', 0x84)
#pragma codepage('┘', 0x85)
#pragma codepage('├', 0x86)
#pragma codepage('┤', 0x87)
#pragma codepage('┬', 0x88)
#pragma codepage('┴', 0x89)
#pragma codepage('┼', 0x8A)
// TODO: #pragma codepage('', 0x8B)
// TODO: #pragma codepage('', 0x8C)
// TODO: #pragma codepage('', 0x8D)
// TODO: #pragma codepage('', 0x8E)
// TODO: #pragma codepage('', 0x8F)

#pragma codepage('░', 0x90)
#pragma codepage('▒', 0x91)
#pragma codepage('▓', 0x92)
// TODO: #pragma codepage('', 0x93)
// TODO: #pragma codepage('', 0x94)
// TODO: #pragma codepage('', 0x95)
// TODO: #pragma codepage('', 0x96)
// TODO: #pragma codepage('', 0x97)
// TODO: #pragma codepage('', 0x98)
// TODO: #pragma codepage('', 0x99)
// TODO: #pragma codepage('', 0x9A)
// TODO: #pragma codepage('', 0x9B)
// TODO: #pragma codepage('', 0x9C)
// TODO: #pragma codepage('', 0x9D)
// TODO: #pragma codepage('', 0x9E)
// TODO: #pragma codepage('', 0x9F)

#pragma codepage('═', 0xA0)
#pragma codepage('║', 0xA1)
#pragma codepage('╒', 0xA2)
#pragma codepage('ё', 0xA3)
#pragma codepage('╓', 0xA4)
#pragma codepage('╔', 0xA5)
#pragma codepage('╕', 0xA6)
#pragma codepage('╖', 0xA7)
#pragma codepage('╗', 0xA8)
#pragma codepage('╘', 0xA9)
#pragma codepage('╙', 0xAA)
#pragma codepage('╚', 0xAB)
#pragma codepage('╛', 0xAC)
#pragma codepage('╜', 0xAD)
#pragma codepage('╝', 0xAE)
#pragma codepage('╞', 0xAF)

#pragma codepage('╟', 0xB0)
#pragma codepage('╠', 0xB1)
#pragma codepage('╡', 0xB2)
#pragma codepage('Ё', 0xB3)
#pragma codepage('╢', 0xB4)
#pragma codepage('╣', 0xB5)
#pragma codepage('╤', 0xB6)
#pragma codepage('╥', 0xB7)
#pragma codepage('╦', 0xB8)
#pragma codepage('╧', 0xB9)
#pragma codepage('╨', 0xBA)
#pragma codepage('╩', 0xBB)
#pragma codepage('╪', 0xBC)
#pragma codepage('╫', 0xBD)
#pragma codepage('╬', 0xBE)
#pragma codepage('©', 0xBF)

#pragma codepage('ю', 0xC0)
#pragma codepage('а', 0xC1)
#pragma codepage('б', 0xC2)
#pragma codepage('ц', 0xC3)
#pragma codepage('д', 0xC4)
#pragma codepage('е', 0xC5)
#pragma codepage('ф', 0xC6)
#pragma codepage('г', 0xC7)
#pragma codepage('х', 0xC8)
#pragma codepage('и', 0xC9)
#pragma codepage('й', 0xCA)
#pragma codepage('к', 0xCB)
#pragma codepage('л', 0xCC)
#pragma codepage('м', 0xCD)
#pragma codepage('н', 0xCE)
#pragma codepage('о', 0xCF)

#pragma codepage('п', 0xD0)
#pragma codepage('я', 0xD1)
#pragma codepage('р', 0xD2)
#pragma codepage('с', 0xD3)
#pragma codepage('т', 0xD4)
#pragma codepage('у', 0xD5)
#pragma codepage('ж', 0xD6)
#pragma codepage('в', 0xD7)
#pragma codepage('ь', 0xD8)
#pragma codepage('ы', 0xD9)
#pragma codepage('з', 0xDA)
#pragma codepage('ш', 0xDB)
#pragma codepage('э', 0xDC)
#pragma codepage('щ', 0xDD)
#pragma codepage('ч', 0xDE)
#pragma codepage('ъ', 0xDF)

#pragma codepage('Ю', 0xE0)
#pragma codepage('А', 0xE1)
#pragma codepage('Б', 0xE2)
#pragma codepage('Ц', 0xE3)
#pragma codepage('Д', 0xE4)
#pragma codepage('Е', 0xE5)
#pragma codepage('Ф', 0xE6)
#pragma codepage('Г', 0xE7)
#pragma codepage('Х', 0xE8)
#pragma codepage('И', 0xE9)
#pragma codepage('Й', 0xEA)
#pragma codepage('К', 0xEB)
#pragma codepage('Л', 0xEC)
#pragma codepage('М', 0xED)
#pragma codepage('Н', 0xEE)
#pragma codepage('О', 0xEF)

#pragma codepage('П', 0xF0)
#pragma codepage('Я', 0xF1)
#pragma codepage('Р', 0xF2)
#pragma codepage('С', 0xF3)
#pragma codepage('Т', 0xF4)
#pragma codepage('У', 0xF5)
#pragma codepage('Ж', 0xF6)
#pragma codepage('В', 0xF7)
#pragma codepage('Ь', 0xF8)
#pragma codepage('Ы', 0xF9)
#pragma codepage('З', 0xFA)
#pragma codepage('Ш', 0xFB)
#pragma codepage('Э', 0xFC)
#pragma codepage('Щ', 0xFD)
#pragma codepage('Ч', 0xFE)
#pragma codepage('Ъ', 0xFF)
